spring:
  application:
    name: Aether Entity Relationship Planning

  datasource:
    username: root
    password: Sangary2026&!.
    url: jdbc:mysql://localhost:3306/aethererpdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    password: phon uzqb nyir tdbx
    username: sangaryousmane@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          from: sangaryousmane@gmail.com
          starttls:
             enable: true
    protocol: smtp

server:
  servlet:
    context-path: /api/v1.0
jwt:
  secret:
    key: lifehasbeenoneofthebestteacherseverinmankindjourney



#  ousmane2026&&!.